Upload test results

diff --git a/.github/workflows/deno.yml b/.github/workflows/deno.yml
--- a/.github/workflows/deno.yml
+++ b/.github/workflows/deno.yml
@@ -1,6 +1,8 @@
-name: Deno CI
+name: 'Deno CI'
 
-on: [push]
+on:
+  - push
+  - pull_request
 
 jobs:
   lint:
@@ -20,6 +22,7 @@ jobs:
           key: ${{ runner.os }}-deno-cache-${{ hashFiles('deno.lock') }}
           restore-keys: |
             ${{ runner.os }}-deno-cache-
+      # Runs deno fmt --check, deno lint, and deno check
       - name: Run linter
         run: deno task check
   test:
@@ -48,6 +51,7 @@ jobs:
           key: ${{ runner.os }}-deno-cache-${{ hashFiles('deno.lock') }}
           restore-keys: |
             ${{ runner.os }}-deno-cache-
+      # Copies the example config with credentials for gh actions db.
       - name: Create test config
         run: |
           cp config.example.jsonc config.jsonc
@@ -58,23 +62,19 @@ jobs:
             -e 's/"ssl": true/"ssl": false/g' \
             config.jsonc
           cp config.jsonc config.test.jsonc
+      # Generates drizzle migrations
       - name: Generate database migrations
         run: deno task db:generate
+      # Applies drizzle migration
       - name: Migrate database
         run: deno task db:migrate
+      # Run deno tests
       - name: Run tests
-        run: deno task test --junit-path report.xml
+        run: deno task test --junit-path test-report.xml
 
-        # Report test results
-#      - name: Test Report
-#        uses: dorny/test-reporter@v1
-#        if: success() || failure()    # run this step even if previous step failed
-#        with:
-#          name: JEST Tests            # Name of the check run which will be created
-#          path: report.xml    # Path to test results
-#          reporter: jest-junit
-      - name: Publish Test Report
-        uses: mikepenz/action-junit-report@v4
-        if: success() || failure() # always run even if the previous step fails
+      - name: "Upload test results"
+        uses: actions/upload-artifact@v4
+        if: success() || failure()        # run this step even if previous step failed
         with:
-          report_paths: 'report.xml'
+          name: test-results
+          path: test-report.xml
